<openerp>
	<data noupdate='0'>

        <record id="excep_order_check_duplicated_webshop_ref" model="sale.exception">
            <field name="name">Duplicated Webshop Reference</field>
            <field name="description">The sale order has a webshop reference which is not unique in the system (for more details see the corresponding issue).</field>
            <field name="sequence">19</field>
            <field name="model">sale.order</field>
            <field name="code">if not order.has_unique_webshop_reference():
                failed = True
            </field>
            <field name="active" eval="True"/>
        </record>

		<record id="excep_no_payment_term" model="sale.exception">
			<field name="name">Sales order does not have a payment term</field>
			<field name="description">The sales order does not have a payment term.</field>
			<field name="sequence">20</field>
			<field name="model">sale.order</field>
			<field name="code">if not order.payment_term:
				failed = True
			</field>
			<field name="active" eval="True" />
		</record>
		
        <record id="excep_order_delivery_method" model="sale.exception">
            <field name="name">Sales order does not have a delivery method</field>
            <field name="description">The sales order does not have a delivery method.</field>
            <field name="sequence">20</field>
            <field name="model">sale.order</field>
            <field name="code">if not order.carrier_id:
                failed = True
            </field>
            <field name="active" eval="True" />
        </record>
        
        <record id="excep_order_payment_method" model="sale.exception">
            <field name="name">Sales order does not have a payment method</field>
            <field name="description">The sales order does not have a paymnet method.</field>
            <field name="sequence">20</field>
            <field name="model">sale.order</field>
            <field name="code">if not order.payment_method_id:
                failed = True
            </field>
            <field name="active" eval="True" />
        </record>
		
        <record id="excep_order_check_credit" model="sale.exception">
            <field name="name">Negative Credit Check.</field>
            <field name="description">The sales order has not passed the credit check process successfully (for more details see the corresponding issue).</field>
            <field name="sequence">21</field>
            <field name="model">sale.order</field>
            <field name="code">if order.is_sale_order_rejected_because_of_creditworthiness():
                failed = True
            </field>
            <field name="active" eval="True"/>
        </record>

	</data>
</openerp>
